version: "3"

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  # api:
  #   container_name: e-commerce
  #   image: vitormsp/e-commerce
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - postgres